default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workypad-development

test:
  <<: *default
  database: workypad-test

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: workypad_production
  username: workypad
  password: <%= ENV["POSTGRES_PASSWORD"] %>
