service: workypad
image: carsoncole/workypad

servers:
  web:
    hosts:
      - 67.207.80.137
    labels:
      traefik.http.routers.domain.rule: Host(`workypad.com`)
      traefik.http.routers.domain.entrypoints: websecure
      traefik.http.routers.domain.tls.certresolver: letsencrypt


registry:
  username: carsoncole
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 67.207.80.137
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

accessories:
  db:
    image: postgres:15
    host: 67.207.80.137
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'workypad'
        POSTGRES_DB: 'workypad_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

traefik:
  # host_port: 8080
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "workypad.com"
    certificatesResolvers.letsencrypt.acme.email: "carson.cole@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

